### ISSUE TITLE
Initialising with --watch arg causes CrashLoopBackOff

### ISSUE THREAD

**Issue by TommyBeaton** [bluebrown/kobold#26]
When I deploy with the example manifest with a reference to: https://github.com/bluebrown/kobold//manifests/dist/?rev=main in my Kustomize file it pulls in the manifests/base/deployment.yaml which [initialises the image with the --watch arg](https://github.com/bluebrown/kobold/blob/main/manifests/base/deployment.yaml#L26). This then causes the following error: 
<img width="989" alt="image" src="https://github.com/bluebrown/kobold/assets/19375325/ccdc909b-acbf-4815-9f75-baa69c7e25ed">
I currently have the deployment file deployed manually without this line and Kobold is now working perfectly.

**Comment by bluebrown** [comment]
Looks like you are not using the latest version of kobold. The flag was added in v0.2.0. I will release a new version soon, which includes docs updates and improved artifact generation, to ensure the right versions are references there.

**Comment by bluebrown** [comment]
This should be better now with the release https://github.com/bluebrown/kobold/releases/tag/v0.2.1. 

The example will now reference the manifests from the release page, which contains the correct tags. If you are currently referencing the dist from main, that is broken now. Perhaps I should have released it as breaking change. 

Sorry, for the delay. I didnt see your response in the message flood in my inbox. And thanks for reporting.
