### ISSUE TITLE
Support endpoint for self-hosted registry

### ISSUE THREAD

**Issue by josias-brenner** [bluebrown/kobold#30]
Notifications coming from the [Open Source Docker Registry](https://github.com/distribution/distribution) (`registry:2` repository on dockerhub) are currently not supported. The format of an individual event seems to be similar to Azure Container Registry, but the WebHook sends an array of events in the request body.

The following is an example-payload from [their documentation](https://docs.docker.com/registry/notifications/):
```json
{
  "events": [
    {
      "id": "320678d8-ca14-430f-8bb6-4ca139cd83f7",
      "timestamp": "2016-03-09T14:44:26.402973972-08:00",
      "action": "pull",
      "target": {
        "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
        "size": 708,
        "digest": "sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf",
        "length": 708,
        "repository": "hello-world",
        "url": "http://192.168.100.227:5000/v2/hello-world/manifests/sha256:fea8895f450959fa676bcc1df0611ea93823a735a01205fd8622846041d0c7cf",
        "tag": "latest"
      },
      "request": {
        "id": "6df24a34-0959-4923-81ca-14f09767db19",
        "addr": "192.168.64.11:42961",
        "host": "192.168.100.227:5000",
        "method": "GET",
        "useragent": "curl/7.38.0"
      },
      "actor": {},
      "source": {
        "addr": "xtal.local:5000",
        "instanceID": "a53db899-3b4b-4a62-a067-8dd013beaca4"
      }
    }
  ]
}
```

If you're open to a PR, I could try implementing support for this myself, although I'm not that experienced in Go and Open Source contributions. My first Idea was to modify `PayloadHandler` to return a `PushData` slice and implement a fourth endpoint type.

**Comment by bluebrown** [comment]
@josias-brenner , sorry for the late response. 

Thanks for the suggestion. I was not aware that registry:2 supports events. Support for this would be very welcome. If you can open a pull request, that would be amazing.

**Comment by bluebrown** [comment]
@josias-brenner, thanks. I have released your feature https://github.com/bluebrown/kobold/releases
