### ISSUE TITLE
package uri doesnt handle branches names properly

### ISSUE THREAD

**Issue by bluebrown** [bluebrown/kobold#45]
The current implementation fo the git package uri is pretty buggy. It was a bad idea to go for this custom format after all.

The root of all evil is, of course, regex: https://github.com/bluebrown/kobold/blob/925580b7ac4428cd3d872f0ee1d61b7c27ee55dd/git/pkguri.go#L29

This only works for single word branches like `main` or `trunk`. Something like `my-branch` or `my/branch` will not work.

The reason why the custom parser has been created is because the url package from the stdlib doesnt understand the ssh url for git. For example https://github.com/hashicorp/go-getter/tree/main/helper/url. 

Kustomize can also fetch packages from remote: https://github.com/kubernetes-sigs/kustomize/blob/82ee768212df792aec76636c07c487b40500ce46/cmd/gorepomod/internal/utils/utils.go#L53-L54

**Comment by tsmalls93** [comment]
I ran into this today with hyphenated branches. Should the regex be modified, or do you have another idea on how to fix it?

**Comment by bluebrown** [comment]
Im not really sure. I think it requires a breaking change no matter what. 

Perhaps using a double slash to seperate the path. 
Or maybe split up the params and not use a single url. 
Or use a url but use url parameters properly.

I could never decide so I left it. What do you think?

**Comment by tsmalls93** [comment]
I like the idea of using URL parameters. Maybe something like `git@github.com:some-org/some-repo.git?ref=some-ref&pkg=some-pkg`?

**Comment by bluebrown** [comment]
That would be ok with me. 

Do you want to try and do that?

Idieally this would also solve the situation with the .git suffix, which is kind of strange at the moment. But it doesnt have to, I guess. https://github.com/bluebrown/kobold/blob/main/git/pkguri.go

**Comment by bluebrown** [comment]
I did some experiments with https://github.com/hashicorp/go-getter, regarding this. It kind of looks promising but then it doesnt exaclty work out, as far as I can see. It would be nice though.

**Comment by bluebrown** [comment]
thanks @tsmalls93 , I have build I have build the image here  docker.io/bluebrown/kobold:e6ad83e. You could deploy it for good and do some smoketests.

**Comment by bluebrown** [comment]
@tsmalls93 , I have released your change now https://github.com/bluebrown/kobold/releases. Thanks again
