### ISSUE TITLE
Ability to customize commit message

### ISSUE THREAD

**Issue by tsmalls93** [bluebrown/kobold#48]
I think it would be nice to be able to customize the commit message. Specifically, I am wanting to make it less generic and put the image that is being updated, so maybe it could be in the decoder script.

**Comment by bluebrown** [comment]
Hi @tsmalls93 , we had this in the previous version. I dropped it during rewrite but the code there is already "anticipating" this feature in some way. It tracks the individual changes which you could range over: https://github.com/bluebrown/kobold/blob/05b55de77d573134f92bec4f49a517a14ebfc540/task/handler.go#L28

Previously I did allow the user to provide a go template and would feed the changes and other metadata in.

If you feel adventurous, you could try to implement that and make a PR.
